name = "moltwars-edge"
main = "src/worker.js"
compatibility_date = "2025-02-01"

[[durable_objects.bindings]]
name = "MOLT_DO"
class_name = "MoltHub"

[[migrations]]
tag = "v1"
new_classes = ["MoltHub"]

[vars]
ORIGIN_WS = "ws://159.198.65.214:8080/ws"
ORIGIN_HTTP = "http://159.198.65.214:8080"

routes = ["server.moltwars.xyz/*"]
